export const PATH = {
  HOME: "/",
  MOVIE_DETAILS: "/movie-details",
  TICKET: "/ticket",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  USER_MANAGEMENT: "/admin/user-management",
  MOVIE_MANAGEMENT: "/admin/movie-management",
  NOT_FOUND: "*",
  ADMIN_USER_MANAGEMENT: "/admin/user-management",
  ADMIN_MOVIE_MANAGEMENT: "/admin/movie-management",
  ADMIN_MOVIE_ADD: "/admin/movie-management/add",
  ADMIN_MOVIE_EDIT: "/admin/movie-management/edit/:id",
  SHOW_TIME: "/admin/movie-management/show-time/:id",
  PROFILE: "/profile",
};
